🔧 Closes #15 update .env.example
coinbase/cdp-wallet-manager pull request #16
Opened 2024-10-17 14:28 UTC by pat-ladon

The .env.example didn't use the `CDP_API_KEY_NAME` and `CDP_API_KEY_SECRET`. Hence, I suggest to update the env example.

2024-10-17 14:29 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-10 05:21 UTC, zekemc approved these changes

2024-11-10 05:21 UTC, cb-heimdall commented
Review Error for zekemc @ 2024-11-10 05:21:29 UTC
User must have write permissions to review

2024-11-15 09:18 UTC, dav3yblaz3 reviewed
The changes look good.  I can provide you with the api if you need it. The app Looks fantastic so far. I need this wallet added as the smart vault. There are also a couple other features I would like to add before we move into testing. Tomorrow do what you can wile I am sleeping I wll be happy to go over ideas soon.

2024-11-16 02:56 UTC, dav3yblaz3 approved these changes

2024-11-16 02:56 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-11-16 02:56:34 UTC
User must have write permissions to review

2024-11-16 03:00 UTC, dav3yblaz3 approved these changes

2024-11-16 03:00 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-11-16 03:00:32 UTC
User must have write permissions to review

2024-11-16 03:47 UTC, dav3yblaz3 approved these changes

2024-11-16 03:47 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-11-16 03:47:04 UTC
User must have write permissions to review

2024-11-16 05:15 UTC, dav3yblaz3 approved these changes

2024-11-16 05:15 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-11-16 05:15:58 UTC
User must have write permissions to review

2024-11-16 06:47 UTC, dav3yblaz3 approved these changes
Sounds good to me. Lets keep working. Need to get everything unified so that it can be managed properly. Thank you!

2024-11-16 06:47 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-11-16 06:47:25 UTC
User must have write permissions to review

2024-11-16 06:57 UTC, dav3yblaz3 approved these changes
Thank you

2024-11-16 06:57 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-11-16 06:57:40 UTC
User must have write permissions to review

2024-11-16 06:58 UTC, dav3yblaz3 requested changes
Please get his working. Let me know what I can do to help. Can you guys help me set up bun?

2024-11-16 06:58 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-11-16 06:58:53 UTC
User must have write permissions to review

2024-11-16 07:55 UTC, add-support-sepolia commented
> The .env.example didn't use the `CDP_API_KEY_NAME` and `CDP_API_KEY_SECRET`. Hence, I suggest to update the `.env.example` to align with `README.md` 

-

2024-12-08 05:43 UTC, zekemc approved these changes

2024-12-08 05:43 UTC, cb-heimdall commented
Review Error for zekemc @ 2024-12-08 05:43:12 UTC
User must have write permissions to review

2024-12-08 07:15 UTC, dav3yblaz3 approved these changes

2024-12-08 07:15 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-12-08 07:15:51 UTC
User must have write permissions to review

2024-12-08 07:55 UTC, add-support-sepolia commented
✋

2024-12-26 08:18 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-12-26 08:18:04 UTC
User must have write permissions to review

2024-12-26 08:18 UTC, dav3yblaz3 approved these changes

2024-12-26 08:18 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2024-12-26 08:18:09 UTC
User must have write permissions to review

2024-12-26 08:18 UTC, dav3yblaz3 approved these changes
ok for test

2025-02-20 01:11 UTC, dav3yblaz3 approved these changes
let us get this going for test thank you team

2025-02-20 01:11 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2025-02-20 01:11:21 UTC
User must have write permissions to review

2025-02-28 17:58 UTC, dav3yblaz3 approved these changes
looks good ok for test thank you team

2025-02-28 17:58 UTC, cb-heimdall commented
Review Error for dav3yblaz3 @ 2025-02-28 17:58:41 UTC
User must have write permissions to review

2025-07-05 12:18 UTC, closed without merging